package core

import (
	"context"
	"github.com/aminsalami/repartido/internal/discovery"
	"github.com/aminsalami/repartido/internal/discovery/adaptors"
	grpc "github.com/aminsalami/repartido/proto/discovery"
	"go.uber.org/zap"
	googleGrpc "google.golang.org/grpc"
	"net"
	"time"
)

var logger = zap.NewExample().Sugar()
var DServer *DiscoveryServer

// DiscoveryServer implements StatusApiServer generated by protoc-gRPC
type DiscoveryServer struct {
	cacheService *cacheService
	grpc.UnimplementedDiscoveryApiServer
}

// -----------------------------------------------------------------

func (s DiscoveryServer) Get(ctx context.Context, req *grpc.StatusRequest) (*grpc.StatusResponse, error) {
	return &grpc.StatusResponse{}, nil
}

// GetRing returns the latest virtual nodes on the ring along with their actual node info.
// Agents request the ring so that they could set up the same ring locally
func (s DiscoveryServer) GetRing(ctx context.Context, _ *grpc.Empty) (*grpc.StatusListResponse, error) {
	tmp := make(map[*discovery.CacheNode][]int32)
	for idx, vnode := range s.cacheService.listRealNodes() {
		tmp[vnode] = append(tmp[vnode], int32(idx))
	}

	var statuses []*grpc.StatusResponse
	for node, vNumberList := range tmp {
		statuses = append(statuses, &grpc.StatusResponse{
			Name:     node.Name,
			Host:     node.Host,
			Port:     node.Port,
			LastPing: node.LastPing,
			RamSize:  node.RamSize,
			Vnumbers: vNumberList,
		})
	}
	return &grpc.StatusListResponse{Statuses: statuses}, nil
}

func (s DiscoveryServer) Register(ctx context.Context, node *grpc.Node) (*grpc.Response, error) {
	// Create a node entity and register it
	cn := discovery.CacheNode{
		Name:     node.Name,
		Host:     node.Host,
		Port:     node.Port,
		LastPing: time.Now().Format(time.RFC3339),
		RamSize:  node.RamSize,
	}
	if err := s.cacheService.registerNode(cn); err != nil {
		return &grpc.Response{Ok: false, Message: err.Error()}, err
	}
	return &grpc.Response{Ok: true, Message: "Done!"}, nil
}

func (s DiscoveryServer) Unregister(ctx context.Context, _ *grpc.Empty) (*grpc.Response, error) {
	return nil, nil
}

func StartServer() {
	l, err := net.Listen("tcp", "localhost:7100")
	if err != nil {
		logger.Fatal(err.Error())
	}

	logger.Info("Starting discovery server on port 7100")
	// Create a new storage adaptor: sqlite
	sqliteStorage := adaptors.NewSqliteCacheStorage()
	s := &DiscoveryServer{
		cacheService: NewCacheService(sqliteStorage),
	}

	grpcServer := googleGrpc.NewServer()
	grpc.RegisterDiscoveryApiServer(grpcServer, s)
	if err := grpcServer.Serve(l); err != nil {
		logger.Fatal(err.Error())
	}
}
